### ISSUE TITLE
API Status: -20 : Control Interface Error

### ISSUE THREAD

**Issue by rmarszew** [cassou/VL53L0X_rasp#5]
I've just downloaded the latest version and having the exactly same output:
Example
VL53L0X PAL Continuous Ranging example

VL53L0X API Version Error: Your firmware has 1.0.2 (revision 4823). This example requires 1.0.1.
Call of VL53L0X_DataInit
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
API Status: -20 : Control Interface Error
API Status: -20 : Control Interface Error
Close Comms
VL53L0X_i2c_close
API Status: -20 : Control Interface Error
pi@raspberrypi:~/scripts/VL/VL53L0X_rasp/bin $

**Comment by FMenziesENG** [comment]
This has just happened to me also. However what is strange is that the sensor is no longer working with code that has previously worked with it.

Using i2cdetect still brings up 0x29 as expected.

It is happening after I have used ^C to exit a custom program which was running the API to read the sensor. Perhaps this has left bad values in the register of the sensor and so has made it not want to continue to be talked to? I'm not an expert in this so I really have no idea though.

I'll return if I find any solution to this.

**Comment by FMenziesENG** [comment]
Having just replaced the bad sensor with another one, the example code runs as expected. It looks like for me the VL53L0X onboard microcontroller may need reset or may be permanently corrupted. If I manage to fix the bad sensor I'll let you know.

**Comment by FMenziesENG** [comment]
So turning it off and on again did the trick for me! Works just like before.

**Comment by MaxMarschall** [comment]
@FMenziesENG did you mean rebooting the RPI or is there a way to restart the sensor? Restarting the RPI doesn't work for me. The sensor was working just fine hooking it up directly to the GPIO pins via jumper cables, then I attached it with headers to a perfboard and the error message came up. Now using the jumper wires again the problem persists.

**Comment by FMenziesENG** [comment]
@MaxMarschall To restart the sensor you simply disconnect and reconnect the sensor to the power supply. As far as I remember the datasheet says that this resets the sensor registers to the defaults. I tried to recreate the problem to fully understand this error but after disconnecting and reconnecting the sensor it just kept working ever since.

**Comment by MaxMarschall** [comment]
Now it's working again, weird...just unplugged and replugged the jumper wires. And the perfboard is working as well.

**Comment by MaxMarschall** [comment]
@FMenziesENG I thought it may have been due to a faulty cable, bad soldering job or cables wired in wrongly but I too can’t recreate it. Would be great for future reference if someone could clear it up

**Comment by manmaeta** [comment]
私も同様のエラーに遭遇しました。
奇妙なことに電源のGPIOを抜き差しするとそれは使えるようになりました。
Thank you for your comment.

**Comment by JakobHuesken** [comment]
Hey, I got the same error.
Using the standard address 0x29 everything works fine, but as soon as I try to change it it brings up
`Setting I2C Address to 0x31
Call of VL53L0X_SetAddress
API Status: -20 : Control Interface Error
VL53L0X_SetOffset: 27000
API Status: -20 : Control Interface Error
Sensor Offset: %d -1
VL53L0X_GOOD_ACCURACY_MODE
Set Accuracy
API Status: -20 : Control Interface Error
Timing 20 ms`

**Comment by JakobHuesken** [comment]
Hey I just wanted to let you know that there is an Error in the vl53l0x_multi_example.py
The way the Outputs for the shutdown pins are set high/low in it will not work.

edit: this only applies if you use vl53l0x-python by pimoroni

**Comment by jshaap** [comment]
> Hey I just wanted to let you know that there is an Error in the vl53l0x_multi_example.py
> The way the Outputs for the shutdown pins are set high/low in it will not work.
> 
> edit: this only applies if you use vl53l0x-python by pimoroni

@JakobHuesken Did you find a solution for this?

**Comment by JakobHuesken** [comment]
@jshaap Yes. In the example the wrong addresses are set in 
`tof = VL53L0X.VL53L0X(i2c_address=0x2B)`
and 
`tof1 = VL53L0X.VL53L0X(i2c_address=0x2D)`
when you declare the objects.
After that both sensors are started by 
`tof.open()`
and
`tof1.open()`
respectively.
Then the Shutdown Pins are set High. This is the wrong order.
First of all make sure all sensors are shutdown. You always have to set the addresses to 0x29 in the declaration of the object, because everytime you power them, they reset to this address. After that power sensor 1 and change its address to whatever you want for example 0x21.
Then power sensor 2 and change its address to something else (0x22.)
This way only one sensor at a time gets its address changed and in the end you got x Sensors with different addresses.
`# Setup GPIO for shutdown pins on each VL53L0X`
`GPIO.setmode(GPIO.BCM)`
`GPIO.setup(sensor1_shutdown, GPIO.OUT)`
`GPIO.setup(sensor2_shutdown, GPIO.OUT)`
`#Set all shutdown pins low to turn off each VL53L0X`
`GPIO.output(sensor1_shutdown, GPIO.LOW)`
`GPIO.output(sensor2_shutdown, GPIO.LOW)`
`#Create the objects with the standard address`
`tof = VL53L0X.VL53L0X(i2c_address=0x29)`
`tof1 = VL53L0X.VL53L0X(i2c_address=0x29)`
`#Enable sensor 1 and change its address`
`GPIO.output(sensor1_shutdown, GPIO.HIGH)`
`tof.change_address(0x21)`
`#Enable sensor 2 and change its address`
`GPIO.output(sensor2_shutdown, GPIO.HIGH)`
`tof.change_address(0x21)`

After this you can open the connection and start measuring.
Note that I only showed to relevant things you need to change, you still need the rest of the code.

**Comment by aistico-jhr** [comment]
Happened to me as well. And I was able to resolve this.

In my case the VCC line had been disconnected from the RPi end. What was bizarre was that even without VCC the VL53L0X was visible to `i2cdetect` but the initialization would fail. 

So, as always, remember to check your connections!
